tasks:
  - name: Initial
    command: |
      pip install Fabric python-dotenv
      cp env.example .env
      echo WAGTAIL_WORDPRESS_IMPORTER_SOURCE_DOMAIN=$(gp url 8080) >>.env
      echo BASE_URL=$(gp url 8000) >>.env
      git clone https://github.com/nickmoreton/wagtail-wordpress-import
      cd wagtail-wordpress-import
      git checkout wagtail-3.0
      cd ..
      fab build
      fab start
      fab run-tests
      fab init
      fab run-import

# ports are public to allow the indivual apps to communicate when downloading images etc.
ports:
  - port: 8000
    visibility: public
  - port: 8080
    visibility: public
