version: '3.9'

services:

  wagtail:
    build: .
    volumes:
      - ./example:/app/example # wagtail app
      - ./xml:/app/xml # imported and exported xml files
      - ./log:/app/log # import logs
      - ./wagtail-wordpress-import:/app/wagtail-wordpress-import # the package
    ports:
      - "8000:8000"
    command: python example/manage.py runserver 0:8000
    depends_on:
      - psqldb
    environment:
      - PSQL_HOST=psqldb
      - PSQL_DATABASE=postgres
      - PSQL_USER=postgres
      - PSQL_PASSWORD=example
      - PSQL_PORT=5432

  psqldb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - psqldb:/var/lib/postgresql/data

  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html # comment to hide the WordPress files locally
      - ./xml:/xml:rw # WordPress XML files shared from the container
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  # wordpress: # uncomment to see the WordPress files locally
  mysqldb:
  psqldb: