version: '3.9'

services:

  wagtail:
    build: .
    volumes:
      - ./cms:/app/cms # wagtail app
      - ./xml:/app/xml # imported and exported xml files
      - ./log:/app/log # import logs
      - ./wagtail-wordpress-import:/app/wagtail-wordpress-import # the package
      - ./pyproject.toml:/app/pyproject.toml # poetry
      - ./poetry.lock:/app/poetry.lock # poetry
      - ./setup.cfg:/app/setup.cfg # linting
    ports:
      - "8000:8000"
    command: python cms/manage.py runserver 0:8000
    depends_on:
      - psqldb
    environment:
      - PSQL_HOST=psqldb
      - PSQL_DATABASE=postgres
      - PSQL_USER=postgres
      - PSQL_PASSWORD=password
      - PSQL_PORT=5432

  psqldb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - psqldb:/var/lib/postgresql/data

  wordpress:
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysqldb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpressdb
    ports:
      - "8080:80"
    volumes:
      - ./wordpress:/var/www/html # comment to hide the WordPress files locally
      - ./xml:/xml:rw # WordPress XML files shared from the container
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysqldb:/var/lib/mysql

volumes:
  # wordpress: # uncomment to see the WordPress files locally
  mysqldb:
  psqldb: