# Generated by Django 3.2.7 on 2021-09-09 14:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('wp_post_id', models.IntegerField(blank=True, null=True)),
                ('wp_post_type', models.CharField(blank=True, max_length=255, null=True)),
                ('body', wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PagePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('wp_post_id', models.IntegerField(blank=True, null=True)),
                ('wp_post_type', models.CharField(blank=True, max_length=255, null=True)),
                ('body', wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('wp_post_id', models.IntegerField(blank=True, null=True)),
                ('wp_post_type', models.CharField(blank=True, max_length=255, null=True)),
                ('body', wagtail.core.fields.StreamField([('raw_html', wagtail.core.blocks.RawHTMLBlock())], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
