# Generated by Django 3.2.7 on 2021-11-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0003_auto_20211105_1040"),
    ]

    operations = [
        migrations.AddField(
            model_name="postpage",
            name="wp_post_meta",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
