# Generated by Django 3.2.7 on 2021-11-17 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.author'),
        ),
    ]
