alias dj="python /app/cms/manage.py"
alias djrun="python /app/cms/manage.py runserver 0.0.0.0:8000"
alias djtest="cd /app/wagtail-wordpress-import && python testmanage.py test && cd /app"
alias djimport="python /app/cms/manage.py import_xml xml/export.xml 3"
alias djdelete="python /app/cms/manage.py delete_imported_pages pages PostPage"
