name: linting

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: pip install black==22.3.0 flake8==4.0.1 isort==5.10.1
      - name: Flake8
        run: flake8 ./
      - name: Isort
        run: isort ./ --check
      - name: Black
        run: black ./ --check